# save on .config/tmux/tmux.conf

# for better colors
set -g default-terminal "tmux-256color"

set -as terminal-overrides ',xterm*:RGB'
set -as terminal-overrides ',xterm*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',xterm*:Setqc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# key action
unbind C-b
set-option -g prefix C-u

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# for esc delay
set -sg escape-time 10

# Resizing pane
bind -r C-k resize-pane -U 10
bind -r C-j resize-pane -D 10
bind -r C-h resize-pane -L 10
bind -r C-l resize-pane -R 10

# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

# mouse usage
set -g mouse on

#theme
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark' # or 'light'
# set -g @plugin 'catppuccin/tmux'
# set -g @catppuccin_flavour 'mocha' # or frappe, macchiato, mocha

# run 
run '~/.tmux/plugins/tpm/tpm'
# new
# neww
# splitw -h
# splitw -v
# dont forget to install Tmux Plugin Manager TPM
## run prefix + I
